<?php

return [
    'latest_election_year' => env('LATEST_ELECTION_YEAR', '2025'),
    'ocr_enabled' => env('OCR_ENABLED', false),
    'ocr_on_upload' => env('OCR_ON_UPLOAD', false),
    'ocr_on_demand' => env('OCR_ON_DEMAND', true),
    'rescan_stored_documents' => env('RESCAN_STORED_DOCUMENTS', false),
    'default_agency' => env('DEFAULT_AGENCY', 'matriz-las-naves'),
    'scanner_service_url' => env('SCANNER_SERVICE_URL', 'http://127.0.0.1:8765/scan'),
    'agencies' => [
        'matriz-las-naves' => [
            'name' => 'Matriz - Las Naves',
            'folder' => 'Matriz - Las Naves',
            'document_place' => 'Las Naves',
            'contribution_certificate' => [
                'office' => 'MATRIZ LAS NAVES',
                'address' => 'Calle 10 de octubre y 10 de Agosto',
                'permit' => 'SEPS-INSEPS-DNGRT-TF-2022-0534',
                'office_code' => '0495',
                'registration_date' => '2022-08-04',
                'original_path' => 'formatos/CERTIFICADO_2026.pdf',
            ],
        ],
        'echeandia' => [
            'name' => 'Echeandía',
            'folder' => 'Echeandía',
            'document_place' => 'Echeandía',
            'contribution_certificate' => [
                'office' => 'SUCURSAL ECHEANDÍA',
                'address' => 'Calle Ramón Ulloa y González Suárez',
                'permit' => 'SEPS-INSEPS-DNGRT-PF-2022-0535',
                'office_code' => '19124',
                'registration_date' => '2022-08-04',
                'original_path' => 'formatos/CERTIFICADO_APORTACION_ECHEANDIA.pdf',
            ],
        ],
        'caluma' => [
            'name' => 'Caluma',
            'folder' => 'Caluma',
            'document_place' => 'Caluma',
            'contribution_certificate' => [
                'office' => 'SUCURSAL CALUMA',
                'address' => 'Avenida La Naranja y Sergio Figueroa',
                'permit' => 'SEPS-INSEPS-DNGRT-PF-2021-0069',
                'office_code' => '19630',
                'registration_date' => '2021-10-22',
                'original_path' => 'formatos/CERTIFICADO_APORTACION_CALUMA_2026.pdf',
            ],
        ],
        'san-jose-del-tambo' => [
            'name' => 'San José del Tambo',
            'folder' => 'San José del Tambo',
            'document_place' => 'San José del Tambo',
            'contribution_certificate' => [
                'office' => 'SUCURSAL SAN JOSÉ DEL TAMBO',
                'address' => 'Calle Luis Alberto Estrella entre Ruperto Benavides y Homero Villagómez',
                'permit' => 'SEPS-INSEPS-DNGRT-PF-2022-0091',
                'office_code' => '20262',
                'registration_date' => '2022-04-12',
                'original_path' => 'formatos/CERTIFICADO_APORTACION_SAN_JOSE.pdf',
            ],
        ],
        'montalvo' => [
            'name' => 'Montalvo',
            'folder' => 'Montalvo',
            'document_place' => 'Montalvo',
            'contribution_certificate' => [
                'office' => 'SUCURSAL MONTALVO',
                'address' => 'Avenida 25 de Abril y Avenida Antonia de la Bastida',
                'permit' => 'SEPS-INSEPS-DNGRT-PF-2022-2124',
                'office_code' => '20871',
                'registration_date' => '2022-10-18',
                'original_path' => 'formatos/CERTIFICADO_APORTACION_MONTALVO.pdf',
            ],
        ],
        'quinsaloma' => [
            'name' => 'Quinsaloma',
            'folder' => 'Quinsaloma',
            'document_place' => 'Quinsaloma',
            'contribution_certificate' => [
                'office' => 'SUCURSAL QUINSALOMA',
                'address' => 'Avenida El Progreso y San Lorenzo',
                'permit' => 'SEPS-INSEPS-DNGRT-PF-2022-2174',
                'office_code' => '21075',
                'registration_date' => '2022-12-22',
                'original_path' => 'formatos/CERTIFICADO_APORTACION_QUINSALOMA.pdf',
            ],
        ],
    ],
];
